#ifndef MOVIE_H
#define MOVIE_H

#include <stdio.h>
#include <stdlib.h>

#include "Param.h"
#include "Segment.h"
#include <vector>


namespace bandwidth
{
	class PopDistribution;
	class Segment;
	/*enum PopType
    {
        Uniform,
        Zipf
    };

	class PopDistribution
    {
	public:

		
        double alpha;
        
		PopType popType;
		PopDistribution () {alpha = 1;}
    };*/

    class Movie
    {
	public:
		double pop;
		std::vector<Segment> segs; //generated by Segment* GenSegment(Movie* movies, Param param, RandomGen randomGen);
		//m moives, each movie has x_m segments;
        
		Movie();
		~Movie();

        Movie(int idx, Param &param);
        void Set(int idx, Param &param);

        static Movie* GenMovies(int m, Param &param);

        static PopDistribution DefaultPopDistribution(int popType);
    };
}
#endif
